version: "3"
services: 
    mysql:
        image: "mysql:5.7"
        command: mysqld --user=root
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db/backup:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'join-us-db'
        ports:
        - '3306:3306'
        expose:
        - '3306'
    api:
        depends_on:
            - mysql
        build:
            dockerfile: Dockerfile
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        # environment: 
            # - REDIS_HOST=redis
            # - REDIS_PORT=6379
            # - PGUSER=postgres #default user
            # - PGHOST=postgres #service name
            # - PGDATABASE=postgres #default database
            # - PGPASSWORD=postgres_password
            # - PGPORT=5432